// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type User struct {
	ID             *string `json:"id"`
	FirstName      string  `json:"firstName"`
	LastName       string  `json:"lastName"`
	Email          string  `json:"email"`
	HashedPassword string  `json:"hashedPassword"`
	Permission     int     `json:"permission"`
}
