// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type User struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Email     string `json:"email"`
	Token     string `json:"token"`
}
