version: '3'
services:
  postgres:
    image: 'postgres:latest'
    container_name: 'postgres'
    environment:
      - POSTGRES_PASSWORD=postgres_password
    ports:
      - 5432:5432
    expose:
      - "5432"
    volumes:
      - ./rest-server/pg/db.sql:/docker-entrypoint-initdb.d/db.sql
  chat_service:
    build:
      dockerfile: Dockerfile
      context: './rest-server/gorilla'
    container_name: 'chat_service'
    ports:
      - 8081:8081
  frontend:
    build:
      dockerfile: Dockerfile
      context: '.'
    container_name: 'frontend'
    ports:
      - 80:80
  # redis:
  #   image: 'redis:latest'
  # server:
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./rest-server/express
  #   volumes:
  #     - /app/node_modules
  #     - ./rest-server/express:/app
  #   environment:
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
  #     - PGUSER=postgres
  #     - PGHOST=postgres
  #     - PGDATABASE=postgres
  #     - PGPASSWORD=postgres_password
  #     - PGPORT=5432
  # client:
  #   stdin_open: true
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: .
  #   volumes:
  #     - /app/node_modules
  #     - ./js-client:/app
  # worker:
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./worker
  #   volumes:
  #     - /app/node_modules
  #     - ./worker:/app
  #   environment:
  #     - REDIS_HOST=redis
  #     - REDIS_PORT=6379
